- hosts: all
  vars:
    ansible_host_key_checking: false

    # Workaround if LXC target host does not have python 3 (not by default)
    ansible_python_interpreter: "/usr/bin/python3"
    
  vars_files:
    - vars.yml
  become: true
  become_user: root

  # Ansible tasks stars here..
  tasks:

  - name: set PHP memory limit
    become: yes
    ini_file:
      path: /etc/php/7.3/fpm/php.ini
      section: PHP
      option: memory_limit
      value: 512M


  - name: set PHP post_max_size
    become: yes
    ini_file:
      path: /etc/php/7.3/fpm/php.ini
      section: PHP
      option: post_max_size
      value: 64M

  - name: set PHP upload_max_filesize
    become: yes
    ini_file:
      path: /etc/php/7.3/fpm/php.ini
      section: PHP
      option: upload_max_filesize
      value: 100M

      
  - name: set PHP max_execution_time
    become: yes
    ini_file:
      path: /etc/php/7.3/fpm/php.ini
      section: PHP
      option: max_execution_time
      value: 300
    
  - name: Restart PHP FPM
    shell: "sudo systemctl restart php7.3-fpm.service"         
